# Generated by Django 5.0 on 2024-01-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibicion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
