# Generated by Django 5.0 on 2024-01-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibicion', '0003_alter_producto_descuento_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.PositiveIntegerField(verbose_name='descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
