# Generated by Django 5.0 on 2024-04-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibicion', '0004_alter_producto_descuento_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CALZADO', 'Calzado'), ('JEANS', 'Jeans'), ('VESTIDOS', 'Vestidos')], default='CALZADO', max_length=20, verbose_name='Categoria'),
        ),
    ]
