# Generated by Django 5.0 on 2023-12-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='slider_images/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
