# Generated by Django 5.0 on 2023-12-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_descuentoinformacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentoinformacion',
            name='imagen',
            field=models.ImageField(default='', upload_to='descuentos_images/'),
            preserve_default=False,
        ),
    ]
