# Generated by Django 5.0 on 2023-12-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_descuentoinformacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='Img-descuentos_images/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
