# Generated by Django 5.0 on 2024-01-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_productoindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoindex',
            name='descuento',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
