# Generated by Django 5.0 on 2024-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_alter_productoindex_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoindex',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
