# Generated by Django 5.0 on 2024-01-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_alter_productoindex_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoindex',
            name='descuento',
            field=models.PositiveIntegerField(verbose_name='descuento'),
        ),
        migrations.AlterField(
            model_name='productoindex',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
