# Generated by Django 5.0 on 2024-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=254)),
                ('municipio', models.CharField(max_length=100)),
                ('barrio_vereda', models.CharField(max_length=100)),
            ],
        ),
    ]
