# Generated by Django 5.0 on 2024-03-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Documento'),
        ),
    ]
