# Generated by Django 5.0 on 2024-01-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_direccion_options_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='barrio_vereda',
            field=models.CharField(default='', max_length=150, verbose_name='Barrio o vereda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.CharField(default='', max_length=150, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(default='', max_length=15, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono fijo'),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
