# Generated by Django 5.0 on 2024-04-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_remove_usuario_correo_alter_usuario_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
    ]
