# Generated by Django 5.0 on 2024-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_remove_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('1', 'Entregada'), ('0', 'No entregada')], default='0', max_length=2, verbose_name='Estado'),
        ),
    ]
