# Generated by Django 5.0 on 2024-04-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_remove_compra_subtotal_itemcompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='iva',
        ),
    ]
