# Generated by Django 5.0 on 2024-04-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_remove_compra_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='subtotal',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
