# Generated by Django 5.0 on 2024-04-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_compra_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='subtotal',
            new_name='total',
        ),
    ]
